name: cs229aProject
channels:
  - pytorch
  - defaults
dependencies:
  - matplotlib
  - numpy
  - python=3.6
  - scikit-learn
  - pandas
  - pillow
  - cudatoolkit
  - pytorch
  - torchvision
  - plotly
  - pip:
    - bayesian-optimization
    - keras
    - tensorflow
    - tensorflow-gpu
    - h5py
    - tqdm
    - tensorflow-datasets